import './globals.css'
import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gas hub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta 
        charSet="utf-8" 
        name="Gas hub for Arbitrum"
        content="Gas hub is a tool for Arbitrum users to find the gas prices and gas fees for their transactions."
      />
      <head>
        <link rel="icon" href="/arbitrum-shield.svg" />
      </head>
      <body className={mulish.className}>{children}</body>
    </html>
  )
}
